# Generated by Django 2.2.9 on 2020-05-31 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=225)),
                ('company_address', models.CharField(max_length=225)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phonenumber', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_totalquatity', models.IntegerField(default=10)),
                ('product_availablequantity', models.IntegerField(default=1)),
                ('product_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Company')),
            ],
        ),
    ]
